var coinkite = require('./coinkite-helper');
var bitcore = require('bitcore');
var _ = require('lodash');
var Wallet = require('./wallet').Wallet;

var keys = [
    {
        //priv in Coinkite's possession
        //m/0: 12MdK9vE8nkEjj5UEz2kyHK9p9JqqMVS4i
        pub: 'xpub661MyMwAqRbcGWgcbzgTxQXHz71cstnhGS54Ho6fRy39EaJFYbQBhUCXJm5wsiZtzAhajJScjJEFaiTSbfcAhbGbC8fKDRwyQz6utFup1UH'
    },
    {
        //cosigner: "3A8897D631-EBDFD1"
        //m/0: 1KavCAxKWgQKbfWGgNhNyB8BZzoWTZA5Xh
        priv: 'xprv9s21ZrQH143K2vQPnZbpt5rdZoVUNsGSkvA5Usxmtf1sKu1hthgvc7U49DeixZHNAwPnQWq9hyCB37SdTddVYwyiEt7m6sJcrLMQp75QcBu',
        pub: 'xpub661MyMwAqRbcFQUrtb8qFDoN7qKxnKzJ895gHGNPSzYrChLrSF1B9unXzWTHXYTcMTZrjsijWnbEJG3QjZ4Qdy9mdc56HQawfqFcVP8VxpW'
    },
    {
        //cosigner: "7EA20DAC2C-48BA4E"
        //m/0: 18aWaxB9h3JQ4pPRtW1wSAknRMNNPsFmdD
        priv: 'xprv9s21ZrQH143K27KwUhjnfmJH4jFZzCEqu1CkJzaa1FM9JexvBrmCxJ87p5VPqY8Uh7495zwyi62HSVCAwDMsL1F8qkFroDPQdiQ6iWdfadL',
        pub: 'xpub661MyMwAqRbcEbQQajGo2uF1cm64PexhGE8M7NzBZat8BTJ4jQ5TW6SbfLfvfXvtViGNdJsrRe3Wkv4Y2ZpnVVPuTDEa3gek96dU5LunXKv'
    }];
var publicKeys;
/**
 * Returns a p2sh address as generated by Coinkite, given the HD public keys. (Derivation path "m/x")
 * @param {Array} hdPublicKeys The xpub strings.
 * @param {int} index The index to be used in the derivation path (The "x" in "m/x").
 * @param {int} requiredSignatures The number of signatures required to spend.
 * @returns {*}
 */
function getReceiveAddress(hdPublicKeys, index, requiredSignatures){
    var derivedPublicKeys = hdPublicKeys.map(function(pubString){
        return (new bitcore.HDPublicKey(pubString))
            .derive('m/' + index)
            .publicKey;
    });
    console.log(derivedPublicKeys.map(function(pub) {
        console.log('public key:' + pub);
        return bitcore.Address.fromPublicKey(pub, bitcore.Networks.livenet);
    }));
    publicKeys = derivedPublicKeys;
    return new bitcore.Address(derivedPublicKeys, requiredSignatures);
}

var wallet = new Wallet({
    account: 'coinfabrik',
    keys: keys,
    cosigners: 3,
    threshold: 2
});

wallet.send('1JPzktin88qmzFJDYEDCDiWFDrBt1vuyi8', 0.001).then(function() {
    console.log('Funds sent!');
});

/*

console.log(bitcore.Address.fromPublicKey(new bitcore.HDPublicKey(keys[2].priv, bitcore.Networks.livenet).publicKey, bitcore.Networks.livenet));
var hdkey = (new bitcore.HDPrivateKey(keys[2].priv, bitcore.Networks.livenet))
    .derive('m/0');
console.log(hdkey.privateKey.toAddress() + '\n' + hdkey.privateKey.toWIF());
console.log('Signature:' + require('./sign').getSignature(hdkey.privateKey, "375030f6a5271727f4c9cebc322e1cf73c979f2dfda226d57dbfbc4b556e4c04"));
var p2shAddress = getReceiveAddress(_.pluck(keys, 'pub'), 0, 2);
console.log(p2shAddress.publicKey);

function callbackGenerico(error, response, body) {
    if (!error && response.statusCode == 200) {
        //var info = JSON.parse(body);
        try {
            console.log(JSON.stringify(body));
        }
        catch(e) {
            console.log(body);
        }
    } else {
        console.log(body);
        console.log(error);
        console.log(response.statusCode);
    }
}

coinkite.request('/v1/co-sign/9B41B8A6FE-4538BE/7EA20DAC2C-48BA4E/sign', 'PUT', {
    signatures: [['304402202c848476cdd2f62c6050e4fbcea73e25eb075dcc83c29efbaef6ae3bf5651fb30220169bf4ecff9c6a239c5efe8058ec35ed4d21981ebb00f10530aca77acd39b82b01',
        '375030f6a5271727f4c9cebc322e1cf73c979f2dfda226d57dbfbc4b556e4c04',
        '0'
    ]]
},callbackGenerico);
*/
//coinkite.request('/v1/co-sign/9B41B8A6FE-4538BE', 'GET', {},callbackGenerico);

//process.exit();
/*
    coinkite.request('/v1/new/send', 'PUT', {
        amount: '0.0003',
        account: 'coinfabrik',
        dest: '1JPzktin88qmzFJDYEDCDiWFDrBt1vuyi8'
    },callbackGenerico);
*/