var coinkite = require('./coinkite');
var bitcore = require('bitcore');
var _ = require('lodash');
var keys = [
    {
        //priv in Coinkite's possession
        pub: 'xpub661MyMwAqRbcGWgcbzgTxQXHz71cstnhGS54Ho6fRy39EaJFYbQBhUCXJm5wsiZtzAhajJScjJEFaiTSbfcAhbGbC8fKDRwyQz6utFup1UH'
    },
    {
        priv: 'xprv9s21ZrQH143K2vQPnZbpt5rdZoVUNsGSkvA5Usxmtf1sKu1hthgvc7U49DeixZHNAwPnQWq9hyCB37SdTddVYwyiEt7m6sJcrLMQp75QcBu',
        pub: 'xpub661MyMwAqRbcFQUrtb8qFDoN7qKxnKzJ895gHGNPSzYrChLrSF1B9unXzWTHXYTcMTZrjsijWnbEJG3QjZ4Qdy9mdc56HQawfqFcVP8VxpW'
    },
    {
        priv: 'xprv9s21ZrQH143K27KwUhjnfmJH4jFZzCEqu1CkJzaa1FM9JexvBrmCxJ87p5VPqY8Uh7495zwyi62HSVCAwDMsL1F8qkFroDPQdiQ6iWdfadL',
        pub: 'xpub661MyMwAqRbcEbQQajGo2uF1cm64PexhGE8M7NzBZat8BTJ4jQ5TW6SbfLfvfXvtViGNdJsrRe3Wkv4Y2ZpnVVPuTDEa3gek96dU5LunXKv'
    }];

/**
 * Returns a p2sh address as generated by Coinkite, given the HD public keys. (Derivation path "m/x")
 * @param {Array} hdPublicKeys The xpub strings.
 * @param {int} index The index to be used in the derivation path (The "x" in "m/x").
 * @param {int} requiredSignatures The number of signatures required to spend.
 * @returns {*}
 */
function getReceiveAddress(hdPublicKeys, index, requiredSignatures){
    var derivedPublicKeys = hdPublicKeys.map(function(pubString){
        return (new bitcore.HDPublicKey(pubString))
            .derive('m/' + index)
            .publicKey;
    });
    return new bitcore.Address(derivedPublicKeys, requiredSignatures);
}

var p2shAddress = getReceiveAddress(_.pluck(keys, 'pub'), 0, 2);
console.log(p2shAddress.toString());
function callbackGenerico(error, response, body) {
    if (!error && response.statusCode == 200) {
        //var info = JSON.parse(body);
        try {
            console.log(JSON.stringify(body));
        }
        catch(e) {
            console.log(body);
        }
    } else {
        console.log(body);
        console.log(error);
        console.log(response.statusCode);
    }
}


//coinkite.request('/v1/co-sign/9B41B8A6FE-4538BE/13B8AE9034-1CC9D9/sign', 'PUT', {},callbackGenerico);

//process.exit();
/*
    coinkite.request('/v1/new/send', 'PUT', {
        amount: '0.0003',
        account: 'coinfabrik',
        dest: '1JPzktin88qmzFJDYEDCDiWFDrBt1vuyi8'
    },callbackGenerico);
*/